package model

// Problem represents a client or server side error
type Problem struct {
	// A short, summary of the problem type. Written in english and readable for engineers (usually not suited for non technical stakeholders and not localized); example: Service Unavailable
	Title string `json:"title,omitempty"`

	// The HTTP status code generated by the origin server for this occurrence of the problem.
	Status int `json:"status,omitempty"`

	// A human readable explanation specific to this occurrence of the problem.
	Detail string `json:"detail,omitempty"`
}
