version: '3.5'
services:
  search_api:
    #container_name: 'search_api'
    #image: 'sgampa/product_search:latest'
    build: .
    restart: 'on-failure'
    ports:
      - '8080:8080'
    depends_on:
      - elasticsearch
  elasticsearch:
    container_name: 'elasticsearch'
    image: 'docker.elastic.co/elasticsearch/elasticsearch:6.4.2'
    ports:
      - '9200:9200'